"""empty message

Revision ID: 17f1803963d6
Revises: 
Create Date: 2020-10-25 03:42:13.170375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f1803963d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epoch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('julian_date', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('julian_date')
    )
    op.create_table('sensor',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sensor_type', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('target',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('ephemeris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('pos_x_km', sa.Float(), nullable=False),
    sa.Column('pos_y_km', sa.Float(), nullable=False),
    sa.Column('pos_z_km', sa.Float(), nullable=False),
    sa.Column('vel_x_km_p_sec', sa.Float(), nullable=False),
    sa.Column('vel_y_km_p_sec', sa.Float(), nullable=False),
    sa.Column('vel_z_km_p_sec', sa.Float(), nullable=False),
    sa.Column('julian_date', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['julian_date'], ['epoch.julian_date'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('azimuth_rad', sa.Float(), nullable=True),
    sa.Column('elevation_rad', sa.Float(), nullable=True),
    sa.Column('range_km', sa.Float(), nullable=True),
    sa.Column('range_rate_km_p_sec', sa.Float(), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('julian_date', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['julian_date'], ['epoch.julian_date'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.unique_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.unique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation')
    op.drop_table('ephemeris')
    op.drop_table('target')
    op.drop_table('sensor')
    op.drop_table('epoch')
    # ### end Alembic commands ###
